"""add pageviews table

Revision ID: af5cb326762b
Revises: ad6faf952ef7
Create Date: 2026-03-11 23:06:10.222629+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af5cb326762b"
down_revision: Union[str, None] = "ad6faf952ef7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pageviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("client_ip", sa.String(length=45), nullable=False),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pageviews_path", "pageviews", ["path"], unique=False)
    op.create_index("ix_pageviews_viewed_at", "pageviews", ["viewed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pageviews_viewed_at", table_name="pageviews")
    op.drop_index("ix_pageviews_path", table_name="pageviews")
    op.drop_table("pageviews")
    # ### end Alembic commands ###
