"""add webhook_subscriptions table

Revision ID: 88427ec10dd1
Revises: b4c8d0e23f56
Create Date: 2026-03-11 22:52:26.568711+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88427ec10dd1"
down_revision: str | None = "b4c8d0e23f56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("webhook_url", sa.Text(), nullable=False),
        sa.Column("webhook_type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("systems", sa.JSON(), nullable=False),
        sa.Column("regions", sa.JSON(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("include_pods", sa.Boolean(), nullable=False),
        sa.Column("ship_types", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("webhook_subscriptions")
    # ### end Alembic commands ###
