"""add_user_subscription_model

Revision ID: d97abf453c56
Revises:
Create Date: 2026-03-03 11:16:19.605365+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d97abf453c56"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index("ix_cache_entries_expires", "cache_entries", ["expires_at"], unique=False)
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("faction_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "route_bookmarks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("from_system", sa.String(length=100), nullable=False),
        sa.Column("to_system", sa.String(length=100), nullable=False),
        sa.Column("profile", sa.String(length=50), nullable=False),
        sa.Column("avoid_systems", sa.Text(), nullable=True),
        sa.Column("use_bridges", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_route_bookmarks_character", "route_bookmarks", ["character_id"], unique=False
    )
    op.create_index(
        op.f("ix_route_bookmarks_character_id"), "route_bookmarks", ["character_id"], unique=False
    )
    op.create_index(
        "ix_route_bookmarks_from_to", "route_bookmarks", ["from_system", "to_system"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("character_name", sa.String(length=100), nullable=False),
        sa.Column("subscription_tier", sa.String(length=20), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("character_id"),
        sa.UniqueConstraint("stripe_customer_id"),
    )
    op.create_table(
        "solar_systems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("constellation_id", sa.Integer(), nullable=True),
        sa.Column("security_status", sa.Float(), nullable=False),
        sa.Column("security_class", sa.String(length=20), nullable=False),
        sa.Column("position_x", sa.Float(), nullable=False),
        sa.Column("position_y", sa.Float(), nullable=False),
        sa.Column("position_z", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_solar_systems_name"), "solar_systems", ["name"], unique=True)
    op.create_index(
        "ix_solar_systems_region_security",
        "solar_systems",
        ["region_id", "security_class"],
        unique=False,
    )
    op.create_table(
        "kill_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("kill_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ship_type_id", sa.Integer(), nullable=True),
        sa.Column("victim_corporation_id", sa.Integer(), nullable=True),
        sa.Column("victim_alliance_id", sa.Integer(), nullable=True),
        sa.Column("attacker_count", sa.Integer(), nullable=False),
        sa.Column("is_pod", sa.Boolean(), nullable=False),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["solar_systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kill_records_system_time", "kill_records", ["system_id", "kill_time"], unique=False
    )
    op.create_table(
        "stargates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_system_id", sa.Integer(), nullable=False),
        sa.Column("destination_system_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_system_id"],
            ["solar_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"],
            ["solar_systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stargates_destination", "stargates", ["destination_system_id"], unique=False
    )
    op.create_index("ix_stargates_source", "stargates", ["source_system_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stargates_source", table_name="stargates")
    op.drop_index("ix_stargates_destination", table_name="stargates")
    op.drop_table("stargates")
    op.drop_index("ix_kill_records_system_time", table_name="kill_records")
    op.drop_table("kill_records")
    op.drop_index("ix_solar_systems_region_security", table_name="solar_systems")
    op.drop_index(op.f("ix_solar_systems_name"), table_name="solar_systems")
    op.drop_table("solar_systems")
    op.drop_table("users")
    op.drop_index("ix_route_bookmarks_from_to", table_name="route_bookmarks")
    op.drop_index(op.f("ix_route_bookmarks_character_id"), table_name="route_bookmarks")
    op.drop_index("ix_route_bookmarks_character", table_name="route_bookmarks")
    op.drop_table("route_bookmarks")
    op.drop_table("regions")
    op.drop_index("ix_cache_entries_expires", table_name="cache_entries")
    op.drop_table("cache_entries")
    # ### end Alembic commands ###
