"""add kill_history table

Revision ID: ad6faf952ef7
Revises: 88427ec10dd1
Create Date: 2026-03-11 23:04:27.910282+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad6faf952ef7"
down_revision: Union[str, None] = "88427ec10dd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kill_history",
        sa.Column("kill_id", sa.Integer(), nullable=False),
        sa.Column("system_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column("is_pod", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("kill_id"),
    )
    op.create_index("ix_kill_history_received", "kill_history", ["received_at"], unique=False)
    op.create_index("ix_kill_history_region", "kill_history", ["region_id"], unique=False)
    op.create_index("ix_kill_history_system", "kill_history", ["system_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_kill_history_system", table_name="kill_history")
    op.drop_index("ix_kill_history_region", table_name="kill_history")
    op.drop_index("ix_kill_history_received", table_name="kill_history")
    op.drop_table("kill_history")
    # ### end Alembic commands ###
